version: '3'
services:
  postgres:
    image: "postgres:14.3-alpine3.16"
    command: postgres -c 'max_connections=1000'
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres-data:
